### ISSUE TITLE
UI Layout Update

### ISSUE THREAD

**Issue by joshuajames-smith** [gliff-ai/annotate#118]
**Is your feature request related to a problem? Please describe.**
The interface design requires updating to reflect gliff'ai's new visual identity but also to improve the UI and UX for users.

**Describe the solution you'd like**
I have applied my previous iteration style to the interface as the features currently stand. [All the screenshots can be accessed through the Adobe XD prototype link at the end].

![Interface Layout -  empty](https://user-images.githubusercontent.com/83074763/116738108-f0f51600-a9e9-11eb-903b-f813ccf01f23.png)

I've added the new logo and changed the image upload icon. The toolbar continues to be a floating element that should hug the bottom left corner with about 17/18px space. The minimap sits flush to the screen corner in the bottom right.

These next three images show the icon states: no interactive, hover, and click.

![Tool Bar -  no interaction](https://user-images.githubusercontent.com/83074763/116738877-f30ba480-a9ea-11eb-8326-f9cfa5a47e98.png)
![Tool Bar -  hover interaction](https://user-images.githubusercontent.com/83074763/116738889-f6069500-a9ea-11eb-8b5b-efcfd6f59682.png)
![Tool Bar -  pressed down interaction](https://user-images.githubusercontent.com/83074763/116738903-f9018580-a9ea-11eb-8a14-bac16951a185.png)

This next image shows how the interaction with once the user has clicked the brush tool can appear. Vertical slider bar with pixel brush size. Thinking this brush tool bar should be hover once the user click the main icon?

![Interface Layout -  toolbar - brush](https://user-images.githubusercontent.com/83074763/116739146-4120a800-a9eb-11eb-9836-71f3a2fd646c.png)

Below is some images of how I anticipate the minimap to be used. State styles remain the same. Expect on the hover state, it is above (not to the side) of the main feature. Kept the zoom in and out hover states to the left and fit to the page on the right to provide some visual belonging. 

![Mini-Map -  no interaction](https://user-images.githubusercontent.com/83074763/116739482-a4123f00-a9eb-11eb-8a26-447ad19c624a.png)
![Mini-Map -  press down interaction](https://user-images.githubusercontent.com/83074763/116739485-a5436c00-a9eb-11eb-8812-6aacf869798b.png)
![Mini-Map -  hover interaction  – 1](https://user-images.githubusercontent.com/83074763/116739495-a96f8980-a9eb-11eb-8ea1-0df627813627.png)
![Mini-Map -  no interaction  – 1](https://user-images.githubusercontent.com/83074763/116739505-aaa0b680-a9eb-11eb-906c-ae10dd6b381d.png)
![Mini-Map -  hover interaction](https://user-images.githubusercontent.com/83074763/116739511-abd1e380-a9eb-11eb-94f2-31bae8166c36.png)

**Describe alternatives you've considered**
I tried to have a think and re-shuffle how the annotation label tool could work/look.
I found the one currently available to be clunky and not make sense how to access each annotation to then view and add/remove labels attached. I also added a pin icon so that users could click the icon, have this menu open and be able to pin it open on their workspace instead of constantly having to hover on the toolbar?
![Interface Layout -  toolbar - annotation labelling](https://user-images.githubusercontent.com/83074763/116738368-42050a00-a9ea-11eb-8a76-edb6c80a09e7.png)
![Tool Bar -   annotation labelling - no interaction](https://user-images.githubusercontent.com/83074763/116738527-7973b680-a9ea-11eb-967e-eb94f681a584.png)
![Tool Bar -   annotation labelling - press down interaction](https://user-images.githubusercontent.com/83074763/116738529-7a0c4d00-a9ea-11eb-90bd-0f0ba11e3f99.png)

**Additional context**
![Adobe XD - tutorial (screenshot)](https://user-images.githubusercontent.com/83074763/116737040-a2934780-a9e8-11eb-9459-467730352041.png)
[https://xd.adobe.com/view/18c9ae6f-9af2-4b55-81c2-992e947ea620-4d9a/](url)

This is a developer hand-off feature built into Adobe XD which can be accessed through the above link. It is an interactive wireframe which allows code to be copied straight from the prototype or properties such as pixel locations are displayed by click on the desired UI component.

_[SVG files of plain icons are in UI/UX Google Drive folder]_

**Comment by joshuajames-smith** [comment]
Updated the tool bar's hover state design so the shortcut keys now liv in a circle than a rounded square.

![Tool Bar -  hover interaction  – v2](https://user-images.githubusercontent.com/83074763/117441399-360ad200-af2d-11eb-80bf-1b5d6cf57638.png)

**Comment by ChrisBaidoo** [comment]
> Updated the tool bar's hover state design so the shortcut keys now liv in a circle than a rounded square.
> 
> ![Tool Bar - hover interaction – v2](https://user-images.githubusercontent.com/83074763/117441399-360ad200-af2d-11eb-80bf-1b5d6cf57638.png)

<img width="321" alt="Screenshot 2021-05-11 at 09 31 46" src="https://user-images.githubusercontent.com/37402968/117785003-0d8c1c00-b23c-11eb-8020-565125d6b53e.png">

Hey Josh, for the Contrast and the Brightness, are we using letters or the "/" "\" ?
There is a disparity between the adobe xd design and this one here.

Thanks

**Comment by joshuajames-smith** [comment]
Hey Chris! Sorry for the confusion, I did not realise I had assigned two tools to "B" shortcut so in the updated design I changed it to "/" and "\" but I'm open to any suggestions or changes made with the shortcuts and how we assign them!

Here is the updated adobe xd link as well: https://xd.adobe.com/view/1930084c-3665-4a3a-908b-fd0c3cfc4192-4c63/

**Comment by ChrisBaidoo** [comment]
Thanks for clarifying Josh

**Comment by joshuajames-smith** [comment]
Updated the tool hint pop-up for the image so now longer shortcuts are made up of a circle attached to each key. Giving us more flexibility in shortcuts assigning.

https://xd.adobe.com/view/680e6dbf-3d7b-4315-979b-aaa30f66bf94-3d5d/

![Mini-Map -  hover interaction   fit to page  – 4](https://user-images.githubusercontent.com/83074763/118288416-535f1380-b4cc-11eb-9d8c-4f6323048504.png)
![Mini-Map -  hover interaction   zoom in  – 4](https://user-images.githubusercontent.com/83074763/118288418-53f7aa00-b4cc-11eb-8463-f992b18b0589.png)
![Mini-Map -  hover interaction   zoom out  – 4](https://user-images.githubusercontent.com/83074763/118288421-53f7aa00-b4cc-11eb-9b49-8f867a8a6a1b.png)

**Comment by ChrisBaidoo** [comment]
Hi Josh,

We have a plus (+) button and a delete button that sits inside the Annotation Label popover at the moment.
The plus button adds a new object for annotation, and the delete button clears any annotation on the canvas. 
We want to move these two buttons out into the main app,  because they will be used a lot especially the plus button.  

<img width="289" alt="Screenshot 2021-05-19 at 11 10 38" src="https://user-images.githubusercontent.com/37402968/118796243-53c42980-b893-11eb-9390-5818a9b65aa6.png">

Would you be able to update your design to take this into consideration? 

Thanks

**Comment by joshuajames-smith** [comment]
Hey Chris,

So, I have pulled out the tools from the pop-up (let's call them "New Annotation" and "Delete Annotation) and placed them in a small toolbar above the toolset (this reflects some of the currate UI layout that I've created thus far). The icons are named as above within our google drive in UI / UX folder. 

![Interface Layout -  empty](https://user-images.githubusercontent.com/83074763/119161031-c595a200-ba50-11eb-8d84-10a79856bd11.png)

I also worked on the minimap as we discussed earlier. I have shifted the locations to add a minimise on the left and keep zoom tools to the right. There is screenshots below of the mini-map in its minimised and maximised state.

![Mini-Map -  no interaction](https://user-images.githubusercontent.com/83074763/119160198-e7425980-ba4f-11eb-90a0-a406deb9068b.png)
![Mini-Map -  hover interaction   fit to page](https://user-images.githubusercontent.com/83074763/119160553-5324c200-ba50-11eb-8170-fd48e62d0c00.png)
![Mini-Map -  hover interaction   zoom out](https://user-images.githubusercontent.com/83074763/119160622-5f108400-ba50-11eb-8eac-f5f8c004461c.png)
![Mini-Map -  hover interaction   zoom in](https://user-images.githubusercontent.com/83074763/119160634-6172de00-ba50-11eb-9340-6fc95e978253.png)
![Mini-Map -  hover interaction   minimise](https://user-images.githubusercontent.com/83074763/119160656-646dce80-ba50-11eb-8170-c84c1262a1a7.png)
![Mini-Map -  minimised interaction   maximise](https://user-images.githubusercontent.com/83074763/119160670-6899ec00-ba50-11eb-8c87-fe65718e587d.png)
![Mini-Map -  hover interaction   maximise](https://user-images.githubusercontent.com/83074763/119160683-6b94dc80-ba50-11eb-92ff-5462c51e45b9.png)

We also spoke about the channels tool, which I have kept simple to that of my thinking following our chat earlier. Just simple tick boxes next to each of the 3 colour channels. Click once to turn on or off.

![Interface Layout -  toolbar - channels](https://user-images.githubusercontent.com/83074763/119160986-b9a9e000-ba50-11eb-84d6-84059f8c8c8a.png)

Revamped the paintbrush icon as well. Created the magic spline tool icon also. All tool icons are kept in our google drive and I have renamed them and organised them into interface folders to help you better understand what is what and where is what!

https://xd.adobe.com/view/a2b2e7ce-cd58-4521-8646-ac3938a509d7-f7e1/
