### ISSUE TITLE
Save annotations button 

### ISSUE THREAD

**Issue by SilviaZeta** [gliff-ai/annotate#219]
**Is your feature request related to a problem? Please describe.**
We need a button for saving annotations.

**Describe the solution you'd like**
?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by joshuajames-smith** [comment]
Assuming the topbar is available, the save function should be placed next to 'upload/download' in the topbar. Tool tip should say 'Save Work' or 'Save Annotations'.
![Interface Layout -  empty  - v1](https://user-images.githubusercontent.com/83074763/123424744-274dac80-d5b9-11eb-9cc6-88dcf3941ff6.png)

If we or when we use the topbar for other navigation features, the save function could live in the the annotation tool bar.
![Interface Layout -  empty  - v2](https://user-images.githubusercontent.com/83074763/123425850-8a8c0e80-d5ba-11eb-9bde-7ec683068f6e.png)


[Icon Location = Google Drive > techteam > UI/UX > icons > annotate > 'Save']
https://xd.adobe.com/view/e73428c7-b600-4175-8327-252b938969a8-b267/
