### ISSUE TITLE
Spline Submenu Styling

### ISSUE THREAD

**Issue by ChasNelson1990** [gliff-ai/annotate#270]
**Is your feature request related to a problem? Please describe.**

The new spline Submenu needs new icon designs, currently just using placeholders:
![image](https://user-images.githubusercontent.com/7795189/126624779-070fb5a4-beb0-429d-b461-3d0937045587.png)

**Describe the solution you'd like**

We need icons for:
- [x] Spline
- [x] Lasso Spline
- [x] Magic Spline
- [x] Close Active Spline
- [x] Fill Spline
- [x] Convert Spline to Paintbrush Annotation

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by ChasNelson1990** [comment]
Relates #269

**Comment by joshuajames-smith** [comment]
![Spline Styling](https://user-images.githubusercontent.com/83074763/126774170-a733e124-85ac-436d-b65a-64321e3df4cd.png)

Icon Order:
- Spline
- Lasso Spline
- Magic Spline
- Close Active Spline
- Fill Spline
- Convert Spline to Paintbrush Annotation

_[Icons are the UI/UX google drive folder]_
