### ISSUE TITLE
Bounding Box Styling

### ISSUE THREAD

**Issue by ChasNelson1990** [gliff-ai/annotate#272]
**Is your feature request related to a problem? Please describe.**

#271 adds a new bounding box tool - essentially the ability to quickly add lots of rectangles around objects of interest in an image.

I can see two ways of using this:
1. I have an image with a small number of different "things" that I want to annotate. For each "thing", I draw a box and apply a label, which may or may not be unique. I then press New Annotation and start again.
2. I have an image with a large number of probably similar "things" and I want to annotate them all. For each "thing", I draw a box but I maybe don't care about labels. Pressing New Annotation each time is a bit annoying.

**Describe the solution you'd like**

1. An icon for this tool
2. A bit of thought about those two use cases - what can we do to make work case 2 easier?

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by joshuajames-smith** [comment]
![Boundary Box Styling](https://user-images.githubusercontent.com/83074763/126779214-1b2c5604-e577-4d7f-8d56-1210f26b16ff.png)

New icon for boundary box. UX will be tackled at a later date.
_[Icons are the UI/UX google drive folder]_
