### ISSUE TITLE
Undo and redo icons

### ISSUE THREAD

**Issue by SilviaZeta** [gliff-ai/annotate#284]
We need icons for the undo and redo buttons.

**Comment by joshuajames-smith** [comment]
Designed an undo and redo icon for annotate.
Icons are in the UI/UX google drive folder, under 'annotate'.

![Icons-91](https://user-images.githubusercontent.com/83074763/127648741-1cd93813-7ca3-43e5-8b10-6089f96908ff.png)
![Icons-90](https://user-images.githubusercontent.com/83074763/127648744-3d8fabcf-bc33-4ef2-8590-b2e8d88025e6.png)
