### ISSUE TITLE
Cant draw a spline at the bottom right of the canvas

### ISSUE THREAD

**Issue by ChrisBaidoo** [gliff-ai/annotate#308]
## Describe the bug

Not sure if this is just me but I cant seem to draw a spline at the bottom right of the canvas. It's like the bottom right area is out of bound and there is a border as to how far you can draw a spline.  

The cursor turns from crosshair to pointer when you move to a certain area. 

## To Reproduce

Go to staging https://staging.gliff.app/

Navigate to annotate

Try drawing a spline at the bottom right of the canvas.

## Screenshots

<img width="1792" alt="Screenshot 2021-08-19 at 15 57 34" src="https://user-images.githubusercontent.com/37402968/130091931-82451eb3-dfe5-44f2-b40d-38176caab837.png">

## System Info (please complete the following information):

- OS: [iOS Catalina]
- Browser [chrome]
- Browser version [Version 92.0.4515.107 ]

**Comment by Kinukeo** [comment]
Is this the same area where we can't use the paintbrush as it is taken up by the invisible annotate minimap?
