### ISSUE TITLE
New background settings icon

### ISSUE THREAD

**Issue by ChasNelson1990** [gliff-ai/annotate#335]
See: https://github.com/gliff-ai/annotate/pull/318

**Comment by joshuajames-smith** [comment]
Icon design for the trust services' button sorted! - located in the google drive as per normal, under techteam > UI/UX > annotate.

![Icons-105](https://user-images.githubusercontent.com/83074763/132717349-b39d10e5-478c-4bc6-8029-c82095a176f1.png)
