### ISSUE TITLE
New annotation transparency icon

### ISSUE THREAD

**Issue by ChasNelson1990** [gliff-ai/annotate#336]
See https://github.com/gliff-ai/annotate/pull/329

**Comment by joshuajames-smith** [comment]
I've designed an icon for the annotation transparency tool button - located in the google drive as per normal, under the annotate folder.

![Icons-94](https://user-images.githubusercontent.com/83074763/132540787-46127bfc-bb56-485f-a5b1-29139d5d9e71.png)
