### ISSUE TITLE
Shortcuts Dialogue Design

### ISSUE THREAD

**Issue by joshuajames-smith** [gliff-ai/annotate#421]
## Is your feature request related to a problem? Please describe

Shortcuts dialogue doesn't have a style designed. #415 

## Describe the solution you'd like

Shortcuts dialogue needs a design in keeping with other UI styling.

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by joshuajames-smith** [comment]
@philhallbio this will want to be apart of the documentation.

@ChasNelson1990 the question is, do we want a dialogue for internal platform viewing (probably better UX?) or just redirect users to documentation?

**Comment by ChasNelson1990** [comment]
For keyboard shortcuts, I think a dialog box is good?
