### ISSUE TITLE
Converting splines to paintbrush crashes the application when there are no active splines

### ISSUE THREAD

**Issue by Kinukeo** [gliff-ai/annotate#449]
## Describe the bug

Converting splines to paintbrush when splines are not in use crashes the application.

## To Reproduce

Steps to reproduce the behaviour:

1.  Access the 'Spline' tool on the toolbar
2.  Click on the 'Convert Spline To Paintbrush' tool

## Expected behaviour

The action should be ignored

## System Info (please complete the following information):

- OS: [Windows]
- Browser [chrome]
- Browser version [95.0.4638.69]
- Also occurs in firefox

**Comment by ChasNelson1990** [comment]
@Kinukeo am I correct in saying that this no longer crashes but just does nothing, as expected? If so, please close.
