### ISSUE TITLE
Crash upon converting spline to paintbrush after function has been performed

### ISSUE THREAD

**Issue by joshuajames-smith** [gliff-ai/annotate#490]
## Describe the bug

Creating spline and pressing 'convert spline to paintbrush' after this function has happened crashed the platform.

## To Reproduce

Steps to reproduce the behaviour:

1.  Go to ANNOTATE
2.  Create spline
3.  Close spline
4.  Convert spline to paintbrush
5.  Convert spline to paintbrush (again)
6.  See error / expected crash

## Expected behaviour

Do we expect user to be able to turn paintbrushes back to splines?

If not,
Disable the button once spline has been converted to paintbrush to prevent this issue? Only active it again on a new annotation but if user returns to this annotation, disable it again.

## Screenshots

![IMG_0657](https://user-images.githubusercontent.com/83074763/143616483-62d30109-2033-4d55-9b49-b323bed33d4c.jpg)

## System Info (please complete the following information):

- OS: iPadOS 15.1
- Browser: chrome
- Browser version: 95.0.4638.50

## Additional context

Sentry alerts:
- The above error occurred in the <sDe> component
- TypeError: undefined is not an object (evaluating 'c.x')
- TypeError: undefined is not an object (evaluating 'i.x')
- TypeError: undefined is not an object (evaluating 'c.x')
- The above error occurred in the <wSe> component
- TypeError: undefined is not an object (evaluating 'A[0].x')

**Comment by ChasNelson1990** [comment]
@joshuajames-smith - am I correct in saying that this no longer crashes? It just fails silently, which I can deal with?

**Comment by ChasNelson1990** [comment]
If so, please close.

**Comment by joshuajames-smith** [comment]
> @joshuajames-smith - am I correct in saying that this no longer crashes? It just fails silently, which I can deal with?

Appears fix, or at least I can't recreate it! Closing this issue now.
