### ISSUE TITLE
Use standard Colour Palette for drawing

### ISSUE THREAD

**Issue by cooper667** [gliff-ai/annotate#50]
Rather than all the paints being green and all the splines being red, we should use a standard palette of colours.

Optionally, we could also allow the user to _select_ a palette to use

@ChasNelson1990 can advise on suitable palettes

**Comment by ChasNelson1990** [comment]
Try using the colour palette defined in figure 4 of https://personal.sron.nl/~pault/data/colourschemes.pdf for all non-active layers (don't use the grey, it's just there for comparison) and then use the current secondary colour provided by the Material-UI css (should be red I think) for the active object as there's no medium red the that colour palette?

This should give us a colour-blind friendly qualitative palette that works well on greyscale images.

**Comment by ChasNelson1990** [comment]
P.S. I don't think it matters if we duplicate colours for non active annotations... we can always change it down the line if it does become a problem.
