### ISSUE TITLE
Zoom and pan lagging

### ISSUE THREAD

**Issue by philipjackson** [gliff-ai/annotate#60]
**Describe the bug**
I'm not sure what caused it but at some point on March 24th the zoom and pan tool (including minimap click/drag) have started to lag noticeably. They were lagging a little bit before, but now it's annoying me.

**To Reproduce**

1.  Click the pan and zoom buttons

**Expected behavior**
Less lag.

**Desktop (please complete the following information):**

- OS: Linux
- Browser Firefox
- Version 85

**Additional context**
Will probably have to use a profiler to figure this out. Low priority.

**Comment by cooper667** [comment]
Seems ok to me (although different device and browser!)
