### ISSUE TITLE
"Mark Annotation As Complete" - no prompt to save annotations

### ISSUE THREAD

**Issue by RoseBunker** [gliff-ai/annotate#657]
## Problem

I was forgetting to use the floppy disk button (Save Annotations), and instead just clicking the tick at top (Mark Annotations as Compete), then the right arrow (Next Image). So I was under the elusion that annotations were being saved as I went... but they weren't.

## Solution

What if there is a pop-up text at the various 'exit' points in ANNOTATE saying 'You have not saved your most recent annotations' and a Save Annotations button.

**Comment by joshuajames-smith** [comment]
Relates to https://github.com/gliff-ai/dominate/issues/493
