### ISSUE TITLE
Allow an image to be passed to the main component 

### ISSUE THREAD

**Issue by cooper667** [gliff-ai/annotate#88]
Rather than the current hardcoded zebrafish or uploading, we should be able to pass in imageData somehow when initialising the package

**Comment by ChasNelson1990** [comment]
This is the code from the old tool:
```
    const {
      imageData,
      imageName,
      annotationData,
    } = window.ANNOTATE_TOOL_OPTIONS;
    // Do we have an image in the page?
    if (imageData) {
      void fetch(`data:image/png;base64,${imageData}`)
        .then((res) => res.blob())
        .then((b) => this.uploadImage(new File([b], imageName), null))
        .then(() => {
          if (annotationData) this.readSplineData(annotationData);
        });
    }
```

The key thing will be updating drawImage.ts so that it can also use ctx.putImageData (or whatever it's called)

**Comment by cooper667** [comment]
As part of this we _could_ keep an uploader but make it a plugin? Seems it would be useful when using the standalone tool

**Comment by ChasNelson1990** [comment]
Notes:
* ANNOTATE would take two optional props: 1) a imageBitmap, 2) an annotation object, which can be passed in by DOMINATE or any other method
* By default ANNOTATE doesn't have the UPLOAD button but rather has a placeholder for it
* In our example we load UPLOAD into the placeholder
* And we should have a second example that autoloads a local image file (like we currently do)
